<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE banco [
    <!ELEMENT banco (cuenta+, cliente+, cuenta_cliente)+>
    <!ELEMENT cuenta (id, saldo)>
    <!ATTLIST cuenta intereses CDATA #REQUIRED>
    <!ELEMENT cliente (nombre, apellidos, id_C)>
    <!ELEMENT cuenta_cliente (#PCDATA)>
    <!ATTLIST cuenta_cliente codigo ID #REQUIRED>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT saldo (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT id_C (#PCDATA)>


]>
<banco>
    <cuenta intereses="cuenta personal">
        <id>5454</id>
        <saldo>195$</saldo>
    </cuenta>
    <cliente>
        <nombre>adonay</nombre>
        <apellidos>Gonzalez</apellidos>
        <id_C></id_C>
    </cliente>
    <cuenta_cliente codigo="Ad12">

    </cuenta_cliente>

</banco>