<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE curso [
    <!ELEMENT curso (alumno+,profesor+,asignatura+)>
    <!ATTLIST curso idCurso ID #REQUIRED>
    <!ENTITY nn "Juan Luís de Todos Los Santos Ramón">
    <!ELEMENT alumno (nombreA, apellidoA+)>
    <!ATTLIST alumno idAlumno ID #REQUIRED>
    <!ATTLIST alumno idcurso IDREF #REQUIRED>
    <!ELEMENT nombreA (#PCDATA)>
    <!ELEMENT apellidoA (#PCDATA)>
    <!ELEMENT profesor (nombreP, apellidoP)>
    <!ATTLIST profesor idProfesor ID #REQUIRED>
    <!ATTLIST profesor idCurso IDREF #REQUIRED>
    <!ELEMENT nombreP (#PCDATA)>
    <!ELEMENT apellidoP (#PCDATA)>
    <!ELEMENT asignatura (#PCDATA)>
    <!ATTLIST asignatura idCurso IDREF #REQUIRED>
]>
<curso idCurso="primeroA">
    <alumno idAlumno="adogonz" idcurso="primeroA">
        <nombreA>adonay</nombreA>
        <apellidoA>gonzalez</apellidoA>
    </alumno>
    <profesor idProfesor="pedro2" idCurso="primeroA">
        <nombreP> &nn;</nombreP>
        <apellidoP>Gonzalez</apellidoP>
    </profesor>
    <asignatura idCurso="primeroA">lengua Castellana</asignatura>
</curso>