=== adogonz23/LND/XPATH/tarea1/discos.dtd
<!ELEMENT listado_discos (disco+)>
<!ELEMENT disco (datos,descripcion)>
<!ATTLIST disco tipo NMTOKEN #REQUIRED>
<!ELEMENT datos (solista,titulo,anio?)>
<!ELEMENT solista (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (cancion+)>
<!ELEMENT cancion (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== adogonz23/LND/XPATH/tarea1/discos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listado_discos SYSTEM "discos.dtd">
<listado_discos>
    <disco tipo="lp">
        <datos>
            <solista>Loquillo</solista>
            <titulo>El ritmo del garaje</titulo>
        </datos>
    <descripcion>
        <cancion>El ritmo del garaje</cancion>
        <cancion>Cadillac solitario</cancion>
    </descripcion>
    </disco>
    <disco tipo="cd">
        <datos>
            <solista>burning</solista>
            <titulo>directo</titulo>
            <anio>2003</anio>
        </datos>
        <descripcion>
            <cancion>cancion 1</cancion>
            <cancion>cancion 2</cancion>
        </descripcion>
    </disco>
</listado_discos>
